controller_list:
  - name: kuka_full_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - KUKA_a1_joint
      - KUKA_a2_joint
      - KUKA_a3_joint
      - KUKA_a4_joint
      - KUKA_a5_joint
      - KUKA_a6_joint
      - KUKA_a7_joint
      - KUKA_a8_joint
