controller_list:
  - name: fake_full_lwr_controller
    joints:
      - KUKA_a1_joint
      - KUKA_a2_joint
      - KUKA_a3_joint
      - KUKA_a4_joint
      - KUKA_a5_joint
      - KUKA_a6_joint
      - KUKA_a7_joint
initial:  # Define initial robot poses.
  - group: full_lwr
    pose: kuka_lwr_home