# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kuka_full
  joint_model_group_pose: kuka_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - KUKA_a1_joint
    - KUKA_a2_joint
    - KUKA_a3_joint
    - KUKA_a4_joint
    - KUKA_a5_joint
    - KUKA_a6_joint
    - KUKA_a7_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: kuka_full_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - KUKA_a1_joint
      - KUKA_a2_joint
      - KUKA_a3_joint
      - KUKA_a4_joint
      - KUKA_a5_joint
      - KUKA_a6_joint
      - KUKA_a7_joint
  - name: kuka_wrist_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - KUKA_a5_joint
      - KUKA_a6_joint
      - KUKA_a7_joint
  - name: kuka_ee_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []