# Author: Saba Mansourfar 
# University: Politecnico Di Milano
# Labratory: NearLAB
#     Robot: Kuka LWR 4+

#  **Important Notice**
#  This will load default Kuka controllers + some specific controllers

KUKA:
  # CONTROLLERS USED
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - KUKA_a1_joint
      - KUKA_a2_joint
      - KUKA_a3_joint
      - KUKA_a4_joint
      - KUKA_a5_joint
      - KUKA_a6_joint
      - KUKA_a7_joint

  gazebo_ros_control:   
    pid_gains:
      KUKA_a1_joint: {p: 250,  i: 10, d: 30}
      KUKA_a2_joint: {p: 220,  i: 10, d: 30}
      KUKA_a3_joint: {p: 150,  i: 6, d: 20}
      KUKA_a4_joint: {p: 150,  i: 5, d: 12}
      KUKA_a5_joint: {p: 90,  i: 5, d: 10}
      KUKA_a6_joint: {p: 40,  i: 5, d: 7}
      KUKA_a7_joint: {p: 15,  i: 2, d: 5}

